export const HOME_REVEAL = {
  heroTitle: {
    durationMs: 1100,
    threshold: 0.3,
    rootMargin: "0px 0px -8% 0px",
    hiddenClassName: "opacity-0 translate-y-[2rem] scale-[0.985] blur-[10px]",
    visibleClassName: "opacity-100 translate-y-0 scale-100 blur-0",
  },
  heroLogo: {
    durationMs: 1000,
    threshold: 0.3,
    rootMargin: "0px 0px -8% 0px",
    hiddenClassName: "opacity-0 translate-y-[2.4rem] scale-[0.96] blur-[10px]",
    visibleClassName: "opacity-100 translate-y-0 scale-100 blur-0",
  },
  heroSubtitle: {
    durationMs: 1080,
    threshold: 0.3,
    rootMargin: "0px 0px -8% 0px",
    hiddenClassName: "opacity-0 translate-y-[2.8rem] blur-[12px]",
    visibleClassName: "opacity-100 translate-y-0 blur-0",
  },
  sectionTitle: {
    durationMs: 900,
    threshold: 0.18,
    rootMargin: "0px 0px 8% 0px",
    hiddenClassName: "opacity-0 -translate-y-[1.6rem] blur-[8px]",
    visibleClassName: "opacity-100 translate-y-0 blur-0",
  },
  textBlock: {
    durationMs: 920,
    threshold: 0.18,
    rootMargin: "0px 0px 10% 0px",
    hiddenClassName: "opacity-0 -translate-x-[2.4rem] blur-[8px]",
    visibleClassName: "opacity-100 translate-x-0 blur-0",
  },
  mediaBlock: {
    durationMs: 980,
    threshold: 0.18,
    rootMargin: "0px 0px 10% 0px",
    hiddenClassName: "opacity-0 translate-x-[2.4rem] scale-[0.985] blur-[10px]",
    visibleClassName: "opacity-100 translate-x-0 scale-100 blur-0",
  },
  sectionBody: {
    durationMs: 960,
    threshold: 0.16,
    rootMargin: "0px 0px 12% 0px",
    hiddenClassName: "opacity-0 translate-y-[2.4rem] blur-[10px]",
    visibleClassName: "opacity-100 translate-y-0 blur-0",
  },
  card: {
    durationMs: 880,
    threshold: 0.14,
    rootMargin: "0px 0px 14% 0px",
    hiddenClassName: "opacity-0 translate-y-[2rem] scale-[0.97] blur-[8px]",
    visibleClassName: "opacity-100 translate-y-0 scale-100 blur-0",
  },
  button: {
    durationMs: 900,
    threshold: 0.16,
    rootMargin: "0px 0px 14% 0px",
    hiddenClassName: "opacity-0 translate-y-[1.6rem] scale-[0.96] blur-[8px]",
    visibleClassName: "opacity-100 translate-y-0 scale-100 blur-0",
  },
} as const;