export const HEADER_CONFIG = {
  SUBMENU_HEIGHT_REM: 6,
  HEIGHTS_REM: {
    PC: 15,
    TABLET: 12,
    MOBILE: 8,
  },
  BREAKPOINTS: {
    DESKTOP: 1024,
    TABLET: 768,
  },
  EXTRA_OFFSET_REM: 2,
} as const;

export const HEADER_HEIGHTS_CSS = {
  PC: `${HEADER_CONFIG.HEIGHTS_REM.PC}rem`,
  TABLET: `${HEADER_CONFIG.HEIGHTS_REM.TABLET}rem`,
  MOBILE: `${HEADER_CONFIG.HEIGHTS_REM.MOBILE}rem`,
  EXTRA_OFFSET: `${HEADER_CONFIG.EXTRA_OFFSET_REM}rem`,
} as const;